# streamlit.yaml - Streamlit UI
apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamlit
  namespace: mlops-diabetes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streamlit
  template:
    metadata:
      labels:
        app: streamlit
    spec:
      containers:
      - name: streamlit
        image: diabetes-streamlit:latest
        ports:
        - containerPort: 8501
---
apiVersion: v1
kind: Service
metadata:
  name: streamlit
  namespace: mlops-diabetes
spec:
  selector:
    app: streamlit
  ports:
  - port: 8501
    targetPort: 8501
  type: LoadBalancer
